#!/bin/sh
case $ZSH_VERSION in '') :;; *) alias -g '${1+"$@"}="$@"';; esac &&
CDPATH= && unset CDPATH

. ./prjlib.sh
. ./spftools.sh
. ./sptools.sh

case $? in 0) :;; *) (exit "$?");; esac &&
{ test "$#" != 0 ||
  prj_fail 'usage: sp-download /package/admin/foo-1.2.3 [...]'; } &&
prj_set prj_program sp-download &&
sp_validate_root &&
prj_set_default SP_OFFLINE_SRC n &&

prj_unset tardir url tmp base ext &&
for tmp in ${1+"$@"}; do
  { tmp=`prj_sedarg1 's%/*$%%' "${tmp?}"` &&
    sp_parse "${tmp?}" &&
    { test '' != "${sp_version?}" ||
      prj_fail "path must include a version: ${sp_path?}"; } &&
    { prj_is_set sp_category ||
      prj_fail "path must be under [\$SP_ROOT]/package: ${sp_path?}"; } &&
    sp_find_tar &&
    { test not_found = "${sp_tar?}" || continue; } &&
    { test n = "${SP_OFFLINE_SRC?}" ||
      prj_fail 'no local tarball was found and SP_OFFLINE_SRC is set'; } &&
    for url in "${sp_root?}" ''; do
      { url=${url?}/package/"${sp_category?}${sp_base?}"/package/url_src &&
        if test -f "${url?}"; then break
        elif test "${url?}" = ''; then prj_fail 'unable to find URL file'
        else :
        fi
      } || exit "$?"
    done &&
    tmp='s%^-%%
s%\([,\\&]\)%\\\1%g' &&
    tmp=`prj_sedarg1 "${tmp?}" "${sp_version?}"` &&
    tmp="s,%{VERSION},${tmp?},g
q" &&
    url=`sed "${tmp?}" < "${url?}"` &&
    base=`prj_basename "${url?}"` &&
    case ${base?} in
      *.tar.bz2) ext=.bz2;;
      *.tar.gz|*.tgz) ext=.gz;;
      *.tar.Z) ext=.Z;;
      *.tar) ext=;;
      *) prj_fail "unrecognized file extension: ${base?}";;
    esac &&
    if prj_is_set SP_TARDIR_FLAT; then tardir=${SP_TARDIR_FLAT?} && tmp=/
    elif prj_is_set SP_TARDIR; then
      tardir=${SP_TARDIR?} && tmp=/${sp_category?}
    else tardir=$SP_ROOT/usr/local/src/package && tmp=/${sp_category?}
    fi &&
    { test -d "${tardir?}"/. || prj_fail "no such directory: ${tardir?}"; } &&
    tardir=${tardir?}${tmp?} &&
    prj_mkdir_p "${tardir?}" &&
    tmp=${tardir?}${sp_base?}${sp_version?}'{tmp}' &&
    mkdir "${tmp?}" &&
    { prj_download "${url?}" "${tmp?}" "${base?}" ||
      prj_savestatus rm -rf "${tmp?}"; } &&
    mv -f "${tmp?}/${base?}" \
      "${tardir?}${sp_base?}${sp_version?}.tar${ext?}" &&
    rmdir "${tmp?}"
  } || exit "$?"
done
