#!/bin/sh
case $ZSH_VERSION in '') :;; *) alias -g '${1+"$@"}="$@"';; esac &&
CDPATH= && unset CDPATH

DIR="$( cd "$( dirname "$0" )" && pwd )"
. ${DIR}/prjlib.sh
. ${DIR}/spftools.sh
. ${DIR}/sptools.sh

case $? in 0) :;; *) (exit "$?");; esac &&
{ test "$#" != 0 ||
  prj_fail 'usage: spf-binary /package/host/example.org/foreign/foo-1.2.3[+spf4] [...]'
} &&
prj_set prj_program spf-binary &&
sp_validate_root &&

spf_download_binary_() {
    spf_tmp_bin_pkg_name=$(basename $1)
    if prj_exists ${sp_dir?}/${spf_tmp_bin_pkg_name?} ; then
      echo "Package ${spf_tmp_bin_pkg_name?} already installed";
      return 0;
    fi
    { prj_download \
          "http://${spf_host?}/slashpackage-foreign/dist/${spf_uname_m?}/${spf_tmp_bin_pkg_name}.tar.gz" \
          ${sp_dir?}/cache/${spf_uname_m?} ${spf_tmp_bin_pkg_name?}.tar.gz || spf_no_binaries_found=1
    }
    cd ${sp_dir?} &&
    tar xf ${sp_dir?}/cache/${spf_uname_m?}/${spf_tmp_bin_pkg_name?}.tar.gz 
} &&
spf_binary_() {
    spf_binary_index_search
    prj_u2 prj_capture spf_tmp_bin_pkg_name spf_binary_index_search &&

    # change the index to just have names, not arch to remove basename
    prj_mkdir_p ${sp_dir?}/cache/${spf_uname_m?} &&
    if test "${spf_tmp_bin_pkg_name?}"; then
      spf_download_binary_ ${spf_tmp_bin_pkg_name?} &&
      ${DIR}/sp-version ${sp_dir?}/${spf_tmp_bin_pkg_name?} &&
      prj_mkdir_p ${sp_dir?}/../command/ &&
      prj_mkdir_p ${sp_dir?}/../library/ &&
      prj_mkdir_p ${sp_dir?}/../include/ &&
      ${DIR}/sp-links ${sp_dir?}/${spf_base?}/command/ ${sp_dir?}/../command/ &&
      ${DIR}/sp-links ${sp_dir?}/${spf_base?}/library/ ${sp_dir?}/../library/ &&
      ${DIR}/sp-links ${sp_dir?}/${spf_base?}/include/ ${sp_dir?}/../include/ &&
      if test -L ${sp_dir?}/${spf_base?}-data; then
        echo "Data dir already exists"
      else
        if test -d ${sp_dir?}/${spf_tmp_bin_pkg_name?}-data; then
          echo "Linking data dir ${sp_dir?}/${spf_tmp_bin_pkg_name?}-data" &&
          cd ${sp_dir?} && ln -s ${sp_dir?}/${spf_tmp_bin_pkg_name?}-data ${sp_dir?}/${spf_base?}-data 
        fi
      fi
      prj_capture spf_tmp_depends_ spf_binary_dependencies ${spf_tmp_bin_pkg_name?}
      for x in ${spf_tmp_depends_?} ; do
          spf_parse "${x?}" &&
          spf_download_binary_ ${x?}
          if test -L ${sp_dir?}/${spf_base?} ; then
            echo "Dependency already has symlink"
          else
            ${DIR}/sp-version ${x?}
          fi
      done 
    else
      echo "No binary found"
    fi
} &&

prj_unset spf_url_ spf_tmp_ spf_tardir_ spf_tmpdir_ &&
for sp_path in ${1+"$@"}; do
  { sp_path=`prj_sedarg1 's%/*$%%' "${sp_path?}"` &&
    case ${sp_path?} in
      /*) :;;
      *) prj_fail "package path must be absolute: ${sp_path?}";;
    esac &&
    spf_parse "${sp_path?}" &&
    spf_binary_index_fetch &&
    eval "set x ${sp_path?}" && shift &&
    while test "$#" != 0; do
      { eval "spf_binary_ $1" &&
        shift
      } || exit "$?"
    done
  } || exit "$?"
done &&
if prj_is_set spf_tmpdir_
  then rm -rf "${spf_tmpdir_?}"
  else :
fi
