#!/bin/sh
case $ZSH_VERSION in '') :;; *) alias -g '${1+"$@"}="$@"';; esac &&
CDPATH= && unset CDPATH

case $? in 0) :;; *) (exit "$?");; esac &&
package/upgrade_version &&
exec package/install_commands
